### ISSUE TITLE
Bad bug

### ISSUE THREAD

**Issue by danzone** [STAMP-project/authzforce-core#7]
ava.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pdp' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Cannot create inner bean 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' of type [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration]: Factory method 'getInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:193)
at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:185)
at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:175)
at org.ow2.authzforce.core.pdp.testutil.test.pep.cxf.Server.run(Server.java:39)
at org.apache.cxf.testutil.common.AbstractTestServerBase.startInProcess(AbstractTestServerBase.java:47)
at org.apache.cxf.testutil.common.ServerLauncher.launchServer(ServerLauncher.java:197)
at org.apache.cxf.testutil.common.AbstractClientServerTestBase.launchServer(AbstractClientServerTestBase.java:90)
at org.ow2.authzforce.core.pdp.testutil.test.pep.cxf.EmbeddedPdpBasedAuthzInterceptorTest.startServers(EmbeddedPdpBasedAuthzInterceptorTest.java:15)

**Comment by cformisano** [comment]
Start Botsing on artifact org.ow2.authzforce:authzforce-ce-core-pdp-testutils:13.3.1 to reproduce the stacktrace in the issue.

**Comment by cformisano** [comment]
Error executing Botsing
